version: "3.9"
services:
  db:
    image: postgres
    command: ["postgres", "-c", "log_checkpoints=off"]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    command:  bash -c "python manage.py makemigrations && python manage.py migrate && pytest"
    #command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev
    volumes:
      - ./toothease:/code
    ports:
      - "8000:8000"
    depends_on:
      - db