# Generated by Django 4.2 on 2024-03-17 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_alter_appointment_kid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaphragmaticBreathing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaphragmatic_breathings', to='appointments.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
