# Generated by Django 4.2 on 2024-04-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaphragmatic_breathing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaphragmaticbreathing',
            options={'verbose_name': 'Diaphragmatic Breathing', 'verbose_name_plural': 'Diaphragmatic Breathings'},
        ),
    ]
