# Generated by Django 4.2.11 on 2024-04-14 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_date_alter_appointment_doctor_and_more'),
        ('diaphragmatic_breathing', '0002_alter_diaphragmaticbreathing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaphragmaticbreathing',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaphragmatic_breathings', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='diaphragmaticbreathing',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
