# Generated by Django 4.2.11 on 2024-04-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaphragmatic_breathing', '0003_alter_diaphragmaticbreathing_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialDiaphragmaticBreathing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveIntegerField(verbose_name='Step')),
                ('image', models.ImageField(upload_to='tutorialDiaphragmaticBreathing', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Tutorial Diaphragmatic Breathing',
                'verbose_name_plural': 'Tutorial Diaphragmatic Breathings',
                'ordering': ('step',),
            },
        ),
    ]
