# Generated by Django 4.2.11 on 2024-04-16 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaphragmatic_breathing', '0004_tutorialdiaphragmaticbreathing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialdiaphragmaticbreathing',
            name='image',
            field=models.ImageField(upload_to='tutorialDiaphragmaticBreathing/', verbose_name='Image'),
        ),
    ]
