# Generated by Django 4.2.11 on 2024-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaphragmatic_breathing', '0005_alter_tutorialdiaphragmaticbreathing_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTutorialDiaphragmaticBreathing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.PositiveIntegerField(verbose_name='Step')),
                ('audio', models.FileField(upload_to='audioTutorialDiaphragmaticBreathing/', verbose_name='Audio')),
            ],
            options={
                'verbose_name': 'Audio Tutorial Diaphragmatic Breathing',
                'verbose_name_plural': 'Audio Tutorial Diaphragmatic Breathings',
                'ordering': ('step',),
            },
        ),
    ]
