# Generated by Django 4.2.11 on 2024-05-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaphragmatic_breathing', '0006_audiotutorialdiaphragmaticbreathing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioTutorialDiaphragmaticBreathing',
        ),
        migrations.AddField(
            model_name='tutorialdiaphragmaticbreathing',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audioTutorialDiaphragmaticBreathing/', verbose_name='Audio'),
        ),
    ]
