# Generated by Django 4.2.11 on 2024-04-14 14:15

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_alter_kid_birth_date_alter_kid_father_alter_kid_name'),
        ('appointments', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(validators=[core.validators.past_date_validator], verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=255, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='kids.kid', verbose_name='Kid'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
