# Generated by Django 4.2 on 2024-04-12 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'verbose_name': 'Kid', 'verbose_name_plural': 'Kids'},
        ),
    ]
