# Generated by Django 4.2.11 on 2024-04-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_alter_kid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kid',
            options={'verbose_name': 'Criança', 'verbose_name_plural': 'Crianças'},
        ),
    ]
